language: node_js
node_js:
  - "node"
after_script: "npm run coveralls"

env:
  - CXX=g++-4.8 DISPLAY=:99.0 ENVNAME=travis

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
